name: Conditional Workflow 2
on: push
jobs:
  number_generator:
    runs-on: ubuntu-latest
      #outputs:
      #abort: ${{ steps.generator.outputs.abort }}
    steps:
      - id: generator
        run: |
          check_one() {
            if [[ $1 == 1 ]]; then
              echo "the result was one"
              echo "ABORT=true" >> $GITHUB_OUTPUT
            fi;
          }

          export NUM=$(($RANDOM % 2))
          echo "num=$NUM"
          check_one $NUM
          echo "gh output = $GITHUB_OUTPUT"
      - name: execute-if-zero
        if: ${{ env.ABORT != 'true' }}
        #if: steps.generator.outputs.abort != 'true'
        run: echo "Executing because result was zero"
      - name: execute-if-one
        if: ${{ env.ABORT == 'true' }}
        #if: steps.generator.outputs.abort == 'true'
        run: echo "Aborting because result was one"
