name: Conditional Workflow
on: push
jobs:
  number_generator:
    runs-on: ubuntu-latest
    outputs:
      num: ${{ steps.generator.outputs.num }}
    steps:
      - id: generator
        run: |
          export NUM=$(($RANDOM % 2))
          echo $NUM
          echo $NUM >> $GITHUB_OUTPUT
          #echo "num=1"
          #echo "num=7" >> $GITHUB_OUTPUT
      - name: echo-zero
        #if: ${{ steps.generator.outputs.num == 0 }}
        if: steps.generator.outputs.num == 0
        run: echo zero
      - name: echo-one
        #if: ${{ steps.generator.outputs.num == 1 }}
        if: steps.generator.outputs.num == 1
        run: echo one
