name: Conditional Workflow
on: push
jobs:
  number_generator:
    runs-on: ubuntu-latest
    steps:
      - id: generator
        run: echo "num=$(($RANDOM % 2))"
      - name: echo-zero
        #if: ${{ steps.generator.outputs.num == 0 }}
        if: steps.generator.outputs.num == 0
        run: echo zero
      - name: echo-one
        #if: ${{ steps.generator.outputs.num == 1 }}
        if: steps.generator.outputs.num == 1
        run: echo one
