name: Conditional Workflow 2
on: push
jobs:
  number_generator:
    runs-on: ubuntu-latest
    steps:
      - id: generator
        run: |
          check_one() {
            if [[ $1 == 1 ]]; then
              echo "the result was one"
              echo "abort=true" >> $GITHUB_OUTPUT
            fi;
          }

          echo "abort=false" >> $GITHUB_OUTPUT
          export NUM=$(($RANDOM % 2))
          echo "num=$NUM"
          check_one $NUM
      - name: execute-if-zero
        if: steps.check-updated-files.outputs.abort == false
        #if: ${{ ! steps.generator.outputs.abort }}
        #if: steps.generator.outputs.abort != 'true'
        run: echo "Executing because result was zero"
      - name: execute-if-one
        if: steps.check-updated-files.outputs.abort == true
        #if: ${{ steps.generator.outputs.abort }}
        #if: steps.generator.outputs.abort == 'true'
        run: echo "Aborting because result was one"
