name: This is a test workflow

on:
  push:
    branches:
      - main

jobs:
  onlyjob:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Attempt-exit-0
        run: |
          echo "Attempting to exit with 0"
          exit 0
      - name: Attempt-exit-1
        run: |
          echo "Exit 0 didn't work, attempting exit 2"
          echo "exit=2"  >> $GITHUB_OUTPUT
          exit 2
      - name: Both-did-not-work
        run: |
          echo "Neither exit 0 nor exit 1 worked, so now we are here"

  if-failed-2:
      runs-on: ubuntu-latest
      needs: [onlyjob]
      permissions:
        issues: 'write'
        actions: 'read'
      if: always() && needs.onlyjob.result == 'failure' && needs.onlyjob.outputs.exit == '2'
      steps:
        - name: Echo on failed
          run: |
            echo "This output is only present if the exit code was 2"
  
  if-failed-other:
      runs-on: ubuntu-latest
      needs: [onlyjob]
      permissions:
        issues: 'write'
        actions: 'read'
      if: always() && needs.onlyjob.result == 'failure' && needs.onlyjob.outputs.exit != '2'
      steps:
        - name: Echo on failed
          run: |
            echo "This output is only present if the exit code was other"
