name: This is a test workflow
# Reference: https://github.com/orgs/community/discussions/25941

on:
  push:
    branches:
      - main

jobs:
  onlyjob:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    outputs:
      exit: ${{ steps.exit-2.outputs.exit }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Attempt-exit-0
        run: |
          echo "Attempting to exit with 0"
          exit 0
      - name: Attempt-exit-5
        id: exit-2
        run: |
          echo "Exit 0 didn't work, attempting exit 5"
          echo "exit=5"  >> $GITHUB_OUTPUT
          echo "exit=5"
          exit 5
      - name: Both-did-not-work
        run: |
          echo "Neither exit 0 nor exit 1 worked, so now we are here"
      - name: run-if-exit-2
        if: ${{ steps.exit-2.outputs.exit == 2 }}
        #if: steps.exit-2.outputs.exit == 2
        run: | 
          echo "I am running if exit was 2"
      - name: run-if-exit-5
        #if: steps.exit-2.outputs.exit == 5
        if: ${{ steps.exit-2.outputs.exit == 5 }}
        run: |
          echo "I am running if exit was 5"
      - name: run-if-exit-not-2
        #if: steps.exit-2.outputs.exit != 2
        if: ${{ steps.exit-2.outputs.exit != 2 }}
        run: |
          echo "I am running if exit was not 2"

  if-failed-2:
      runs-on: ubuntu-latest
      needs: [onlyjob]
      permissions:
        issues: 'write'
        actions: 'read'
      if: always() && needs.onlyjob.result == 'failure' && needs.onlyjob.outputs.exit == '2'
      steps:
        - name: Echo on failed
          run: |
            echo "This output is only present if the exit code was 2: $GITHUB_OUTPUT"
  
  if-failed-other:
      runs-on: ubuntu-latest
      needs: [onlyjob]
      permissions:
        issues: 'write'
        actions: 'read'
      if: always() && needs.onlyjob.result == 'failure' && needs.onlyjob.outputs.exit != '2'
      steps:
        - name: Echo on failed
          run: |
            echo "This output is only present if the exit code was other: $GITHUB_OUTPUT"
